### ISSUE TITLE
No package karamel on opam

### ISSUE THREAD

**Issue by anishathalye** [FStarLang/karamel#300]
The [install instructions](https://github.com/FStarLang/karamel#installing-through-opam) currently refer to "karamel" on opam.

Looks like the kremlin -> karamel renaming didn't include an update to the package name on opam (https://opam.ocaml.org/packages/kremlin/ exists, https://opam.ocaml.org/packages/karamel/ does not).

**Comment by msprotz** [comment]
Maybe @victor-dumitrescu knows how to handle this? He's our local resident OPAM expert :-)

**Comment by msprotz** [comment]
Will this guarantee that when people run "opam upgrade" they'll be switch from kremlin to karamel?

**Comment by victor-dumitrescu** [comment]
Ah, no, this would basically be publishing a new package. I'm not sure there is any way in opam to specify that a new package is a renaming of an old one.

**Comment by victor-dumitrescu** [comment]
Actually seems there is a way: https://opam.ocaml.org/doc/Tricks.html#How-to-rename-a-package

**Comment by msprotz** [comment]
Fixed upstream by @R1kM - thanks!

**Comment by McSinyx** [comment]
Could there please be a Git tag after the rename?  I'm packaging this for Guix and it'd be confusing to have the package name and file names mismatch.

**Comment by protz** [comment]
What prevents you from using a git hash? We've moved towards Nix and track exact git revisions rather than tags.

**Comment by McSinyx** [comment]
Of course tracking the latest commit works, version numbers are just more human-readable, hence I asked if they can be tagged.

**Comment by protz** [comment]
I suggest you stick with the git hashes. Karamel depends on specific versions of F* and Z3 and there is no coordinated version numbering across these projects. I'd rather have the flake.lock be the authoritative source of correct revisions across dependencies than put an arbitrary tag on the project and give users a false sense of stability or an impression that this is official in any way.

**Comment by McSinyx** [comment]
Understandable, is there an ETA for a stable release then?
